FROM alpine:3.20
RUN apk add --no-cache nginx && mkdir -p /run/nginx
COPY tlb/nginx.default.conf /etc/nginx/nginx.conf
COPY tlb/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/docker-entrypoint.sh"]
