services:
  registry:
    build: .
    image: minikitex:local
    command: ["/usr/local/bin/registry"]
    hostname: registry
    environment:
      LISTEN: "0.0.0.0:8500"
    ports:
      - "8500:8500"

  user-1:
    build: .
    image: minikitex:local
    command: ["/usr/local/bin/user"]
    hostname: user-1
    environment:
      LISTEN: "0.0.0.0:8888"
      INSTANCE: user-1
      REGISTRY: "http://registry:8500"
      SERVICE_NAME: "user"
      ADVERTISE: "user-1:8888"
    expose:
      - "8888"
    depends_on:
      - registry

  user-2:
    build: .
    image: minikitex:local
    command: ["/usr/local/bin/user"]
    hostname: user-2
    environment:
      LISTEN: "0.0.0.0:8888"
      INSTANCE: user-2
      REGISTRY: "http://registry:8500"
      SERVICE_NAME: "user"
      ADVERTISE: "user-2:8888"
    expose:
      - "8888"
    depends_on:
      - registry

  order:
    build: .
    image: minikitex:local
    command: ["/usr/local/bin/order"]
    hostname: order-1
    environment:
      LISTEN: "0.0.0.0:8889"
      REGISTRY: "http://registry:8500"
      SERVICE_NAME: "user"
    ports:
      - "8889:8889"
    depends_on:
      - registry
      - user-1
      - user-2
