global:
  scrape_interval: 2s

scrape_configs:
  - job_name: rpc
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: golang
        action: keep
      - source_labels: [__meta_docker_port_private]
        regex: "9091"
        action: keep
      - source_labels: [__meta_docker_container_label_psm]
        target_label: psm
      - source_labels: [__meta_docker_container_label_com_docker_compose_service, __meta_docker_container_label_com_docker_compose_container_number]
        separator: "-"
        target_label: instance
      - source_labels: [__meta_docker_network_ip]
        regex: (.+)
        replacement: $1:9091
        target_label: __address__
